### ISSUE TITLE
Propagate cachePolicy from `URLSession` to `URLRequest`s

### ISSUE THREAD

**Issue by theop-luma** [apple/swift-openapi-urlsession#59]
### Description

When a new URLRequest is created in `swift-openapi-urlsession` it does not inherit cachePolicy from the URLSession provided in the Transport configuration.

### Reproduction

`swift-openapi-urlsession` in `URLSession+Extensions:27`
```
let urlRequest = try URLRequest(request, baseURL: baseURL)
```

### Package version(s)

1.0.2

### Expected behavior

pass cachePolicy from URLSession to URLRequests

### Environment

5.9

**Comment by czechboy0** [comment]
@theop-luma, are you saying that [`URLSession.requestCachePolicy`](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411655-requestcachepolicy) is not being used for requests the URLSession is running? Do I understand correctly?

cc @guoye-zhang

**Comment by guoye-zhang** [comment]
Setting the cache policy on the request is only necessary if you need to override the policy of the session. Otherwise the session’s policy is used.

**Comment by czechboy0** [comment]
Thanks @guoye-zhang, that's what I assumed, so thanks for confirming.

@theop-luma can you clarify whether you're seeing the request _not_ respect the session's cache policy?

**Comment by theop-luma** [comment]
Hmm I am seeing the request not respect the session's cache policy 🤔.

Also the URLRequest initializer seems to have a default `cachePolicy`, not seeing any documentation that the session's cache policy is preferred?
```
public init(url: URL, cachePolicy: URLRequest.CachePolicy = .useProtocolCachePolicy, timeoutInterval: TimeInterval = 60.0)
```

**Comment by guoye-zhang** [comment]
If you don’t set the property on the request, you can assume the session configuration value is used. This is true for other properties like `allowsExpensiveNetworkAccess` as well.

What do you mean by started directly from URLSession?

**Comment by theop-luma** [comment]
Hmmm.. I think you might be right. Having a bit of a hard time getting a clear repro of this, but will reopen if I have something more concrete! Thank you @guoye-zhang and @czechboy0
